extends Node
class_name SBA2

enum WORD_TYPE {
	NOUN_PROPER,
	NOUN_COMMON,
	PRONOUN,
	PRONOUN_DEMONSTRATIVE,
	PRONOUN_POSSESSIVE,
	ADJECTIVE_AS_NOUN,
	ADJECTIVE_TO_NOUN,
	VERB_MAIN,
	VERB_MODAL,
	VERB_HELPING,
	
	ADVERB_TO_ADJECTIVE,
	ADVERB_TO_ADVERB,
	ADVERB_TO_VERB,
	ADVERB_TO_SENTENCE,
	CONJUNCTION_NOUN,
	CONJUNCTION_SUBORDINATING,
	PREPOSITION_SPESIFICATION,
	PREPOSITION_INSTRUMENT,
	PREPOSITION_TO_PHRASAL_VERB,
	
	INFINITIVE
}

func _init():
	pass
